<?
$PERM["bitrix"]["2"]="D";
$PERM["bitrix"]["3"]="D";
$PERM["bitrix"]["4"]="D";
$PERM["bitrix"]["9"]="D";
$PERM["bitrix"]["7"]="D";
$PERM["bitrix"]["8"]="D";
$PERM["bitrix"]["5"]="D";
$PERM["bitrix"]["*"]="D";
$PERM["lk-buyer"]["*"]="D";
$PERM["lk-buyer"]["7"]="X";
$PERM["lk-seller"]["*"]="D";
$PERM["lk-seller"]["8"]="X";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>